#!/bin/bash
set -e

echo "Deploying Lending Protocol Contracts"
echo "====================================="

# Check if Anvil is installed
if ! command -v anvil &> /dev/null; then
    echo "[ERROR] Anvil not found. Please install Foundry:"
    echo "   curl -L https://foundry.paradigm.xyz | bash"
    echo "   foundryup"
    exit 1
fi

# Check if Forge is installed
if ! command -v forge &> /dev/null; then
    echo "[ERROR] Forge not found. Please install Foundry:"
    echo "   curl -L https://foundry.paradigm.xyz | bash"
    echo "   foundryup"
    exit 1
fi

echo "[OK] Foundry tools detected"

# Kill any existing Anvil process
echo "Cleaning up existing Anvil processes..."
pkill -f anvil || true
sleep 1

# Start Anvil in background
echo "Starting Anvil local node..."
anvil --port 8545 --chain-id 31337 > /tmp/anvil.log 2>&1 &
ANVIL_PID=$!
echo "   Anvil PID: $ANVIL_PID"
sleep 2

# Check if Anvil is running
if ! ps -p $ANVIL_PID > /dev/null; then
    echo "[ERROR] Failed to start Anvil"
    cat /tmp/anvil.log
    exit 1
fi

echo "[OK] Anvil running on http://127.0.0.1:8545"

# Build contracts
echo "Building contracts..."
forge build

if [ $? -ne 0 ]; then
    echo "[ERROR] Contract build failed"
    kill $ANVIL_PID
    exit 1
fi

echo "[OK] Contracts built successfully"

# Deploy contracts
echo "Deploying contracts..."

# Deploy MockERC20
echo "   Deploying MockERC20 (Stablecoin)..."
STABLECOIN_OUTPUT=$(forge create --rpc-url http://127.0.0.1:8545 \
    --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
    --broadcast \
    contracts/MockERC20.sol:MockERC20 \
    --constructor-args "USD Stablecoin" "USDC" "1000000000000000000000000")

STABLECOIN_ADDRESS=$(echo "$STABLECOIN_OUTPUT" | grep "Deployed to:" | awk '{print $3}')
echo "   [OK] Stablecoin deployed at: $STABLECOIN_ADDRESS"

# Deploy SimpleLendingProtocol
echo "   Deploying SimpleLendingProtocol..."
PROTOCOL_OUTPUT=$(forge create --rpc-url http://127.0.0.1:8545 \
    --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
    --broadcast \
    contracts/SimpleLendingProtocol.sol:SimpleLendingProtocol \
    --constructor-args "$STABLECOIN_ADDRESS")

PROTOCOL_ADDRESS=$(echo "$PROTOCOL_OUTPUT" | grep "Deployed to:" | awk '{print $3}')
echo "   [OK] Lending Protocol deployed at: $PROTOCOL_ADDRESS"

# Fund protocol with stablecoin
echo "Funding protocol with stablecoin..."
cast send $STABLECOIN_ADDRESS "transfer(address,uint256)" $PROTOCOL_ADDRESS 500000000000000000000000 \
    --rpc-url http://127.0.0.1:8545 \
    --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
    --silent

echo "[OK] Protocol funded"

# Create .env file with deployed addresses
echo "Creating .env file..."
cat > .env << EOF
# Liquidio Configuration
# Auto-generated by deploy_contracts.sh

# Network Configuration
ANVIL_RPC_URL=http://127.0.0.1:8545
ANVIL_WS_URL=ws://127.0.0.1:8545
CHAIN_ID=31337

# Contract Addresses (deployed)
LENDING_PROTOCOL_ADDRESS=$PROTOCOL_ADDRESS
MOCK_TOKEN_ADDRESS=$STABLECOIN_ADDRESS

# Bot Configuration
LIQUIDATOR_PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
MIN_PROFIT_THRESHOLD_USD=10.0
MAX_GAS_PRICE_GWEI=100

# Performance Tuning
MEMPOOL_BATCH_SIZE=100
HEALTH_CHECK_INTERVAL_MS=100

# Logging
RUST_LOG=info,liquidio=debug
EOF

echo "[OK] .env file created"

# Setup test positions
echo "Setting up test positions..."

# Account #1 (will be liquidatable when price drops)
echo "   Creating position for Account #1..."
cast send $PROTOCOL_ADDRESS "deposit()" \
    --value 10ether \
    --rpc-url http://127.0.0.1:8545 \
    --private-key 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d \
    --silent

cast send $PROTOCOL_ADDRESS "borrow(uint256)" 10000000000000000000000 \
    --rpc-url http://127.0.0.1:8545 \
    --private-key 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d \
    --silent

echo "   [OK] Test position created"

echo ""
echo "Deployment Complete!"
echo "===================="
echo "Lending Protocol: $PROTOCOL_ADDRESS"
echo "Stablecoin: $STABLECOIN_ADDRESS"
echo "Anvil PID: $ANVIL_PID"
echo ""
echo "Configuration saved to .env"
echo ""
echo "To stop Anvil: kill $ANVIL_PID"
echo "To run the bot: cargo run --release"
echo ""
